# Generated by Django 4.1.2 on 2022-10-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url_trimmer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveurl",
            name="alias",
            field=models.URLField(default=0, max_length=100),
        ),
    ]
