# Generated by Django 4.1.2 on 2022-10-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url_trimmer", "0003_alter_saveurl_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveurl",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="saveurl",
            name="alias",
            field=models.URLField(default=0, max_length=100, unique=True),
        ),
    ]
