# Generated by Django 4.1.2 on 2022-11-12 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("url_trimmer", "0005_alter_saveurl_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SaveURL",
            new_name="URL",
        ),
        migrations.AlterModelOptions(
            name="url",
            options={"ordering": ("-created_at",)},
        ),
    ]
